### PR TITLE
Add OSX Arm Support

### LINKED ISSUE #1: Improve Feedstock Tests
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Re-work the tests to run during the `test` block in the meta.yaml
https://github.com/conda-forge/staged-recipes/pull/18189#discussion_r817011983

### Installed packages

```shell
na
```

### Environment info

```shell
na
```

### PR DESCRIPTION
**Pull request by SimonBoothroyd**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #1

### CODE REVIEW

**Comment by SimonBoothroyd** [comment]
@conda-forge-admin, please rerender

**Comment by SimonBoothroyd** [comment]
@conda-forge-admin, please rerender

**Comment by SimonBoothroyd** [comment]
@mattwthompson @mikemhenry I think you perhaps have more experience getting OSX ARM builds up. Any advice here?

**Comment by mattwthompson** [comment]
Mike is better with this than me; I looked at your diff and the logs and don't have anything useful to suggest (the structure looks similar to other  repos which successfully build, and I think the error message is misleading or wrong)

```
Packaging nnpops
Packaging nnpops-0.6-cpu_py39h7846a78_0
WARNING: No files or script found for output nnpops
Traceback (most recent call last):
  File "/Users/runner/miniforge3/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/api.py", line 254, in build
    return build_tree(
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/build.py", line 3789, in build_tree
    packages_from_this = build(
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/build.py", line 2877, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/build.py", line 1975, in bundle_conda
    raise CondaBuildException(
conda_build.exceptions.CondaBuildException: Empty package; python present in build and host deps.  You probably picked up the build environment's python  executable.  You need to alter your recipe to  use the PYTHON env var in your recipe to run that executable.
```

Have you tried asking the bot to do the migration? The last time I did it it was a matter of asking their automation nicely and then hoping it works; maybe you did the same thing locally with some tool?

* https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5237/files
* https://github.com/conda-forge/forcebalance-feedstock/pull/31

**Comment by SimonBoothroyd** [comment]
Thanks @mattwthompson ! I'll try some of the changes from that PR, and I found the OpenMM one as well, and if not I'll try to ask the bot!

**Comment by RaulPPelaez** [comment]
I am also struggling with osx arm64 in openmm-plummed. Maybe there are some shared lessons to learn. https://github.com/conda-forge/openmm-plumed-feedstock/pull/32

**Comment by SimonBoothroyd** [comment]
Ah interesting, thanks @RaulPPelaez I'll take a look!

**Comment by SimonBoothroyd** [comment]
Ok looks like it was picking up the wrong python, but that seems to be fixed now. I'll try and get the tests working...

**Comment by SimonBoothroyd** [comment]
@conda-forge-admin, please rerender

**Comment by SimonBoothroyd** [comment]
Ok this should be ready to review! Fixes #1 I think also

**Review by RaulPPelaez — APPROVED** [review]
LGTM! Thanks!

**Comment by mikemhenry** [comment]
:tada: thanks @SimonBoothroyd :raised_hands:

**Pull request merged**
