### PR TITLE
Release NNPOps 0.3

### PR DESCRIPTION
**Pull request by raimis**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by raimis** [comment]
@conda-forge-admin, please rerender

**Comment by raimis** [comment]
@mikemhenry could you review?

**Comment by mikemhenry** [comment]
I am going to see if I can get it to build also for python 3.11

**Comment by mikemhenry** [comment]
Actually, I will merge this in as is, and try 3.11 in a new PR.

**Pull request merged**
