### PR TITLE
Add support for OSX

### PR DESCRIPTION
**Pull request by SimonBoothroyd**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SimonBoothroyd** [comment]
@conda-forge-admin, please rerender

**Comment by SimonBoothroyd** [comment]
@conda-forge-admin, please rerender

**Comment by SimonBoothroyd** [comment]
@conda-forge-admin, please rerender

**Comment by SimonBoothroyd** [comment]
Looks like all the tests are coming back green, so this should be ready for review!

The patch should only need to be temporary until https://github.com/openmm/NNPOps/pull/115 is resolved

**Review by RaulPPelaez — APPROVED** [review]
Looks good to me! Thank you so much! We are not really familiar with OSX so we had not gotten around this.

Have you tested locally with a GPU?

**Comment by SimonBoothroyd** [comment]
Thanks! As far as I know CUDA isn't available on OSX, but when I tested the non-CUDA build locally with this patch it seemed to work great!

**Pull request merged**
